version: "3"  # Versión de Docker Compose que se está utilizando

services:  # Definición de los servicios que se ejecutarán

  mosquitto:  # Nombre del servicio, en este caso, el servidor Mosquitto
    image: eclipse-mosquitto:2.0.18  # Imagen Docker a utilizar para el servidor Mosquitto
    container_name: mosquitto  # Nombre del contenedor que se creará a partir de esta imagen
    environment:  # Variables de entorno que se pasarán al contenedor
      - TZ=Europe/Madrid  # Configuración de la zona horaria del contenedor (opcional)
    volumes:  # Volumenes para montar directorios del host en el contenedor
      - /home/cvp/Entrega-2-iot/mosquitto/config:/mosquitto/config  # Montaje del directorio de configuración del servidor Mosquitto y almacena los certificados
      - /home/cvp/Entrega-2-iot/mosquitto/data:/mosquitto/data  # Montaje del directorio de datos del servidor Mosquitto
      - /home/cvp/Entrega-2-iot/mosquitto/log:/mosquitto/log  # Montaje del directorio de logs del servidor Mosquitto
      - /home/cvp/Entrega-2-iot/mosquitto/certs:/mosquitto/certs  # Montaje del directorio de logs del servidor Mosquitto
      
     # - /home/cvp/Entrega-2-iot/app/contras:/mosquitto/config/passwd

    ports:  # Mapeo de puertos entre el host y el contenedor
      - 8883:8883  # Puerto 8883 del host mapeado al puerto 8883 del contenedor para conexiones MQTT sobre TLS
    restart: unless-stopped  # Política de reinicio del contenedor en caso de fallo o reinicio del sistema (en este caso, reinicia a menos que se detenga manualmente)
    hostname: Entrega-2